### ISSUE TITLE
How can I fetch or create ticket using this api bundle.

### ISSUE THREAD

**Issue by wkm97** [papnoisanjeev/api-bundle#1]
I tried to fetch some tickets using the rest API by referencing https://www.uvdesk.com/en/api-doc/ documentation. But it shows route not found, so I found out that the route available is as the following:
![image](https://user-images.githubusercontent.com/31875755/72715663-dcea2400-3bab-11ea-9a72-ba26c7a2c389.png)

Then I tried to fetch using the route shown
![image](https://user-images.githubusercontent.com/31875755/72715746-ff7c3d00-3bab-11ea-860f-82dd74721a5c.png)

and the error below occurred.
![image](https://user-images.githubusercontent.com/31875755/72715829-29cdfa80-3bac-11ea-9a52-2b2d5e49b58c.png)

Not sure what's the correct way to fetch and create a ticket.

**Comment by papnoisanjeev** [comment]
@wkm97  

This is the main Repository where Api bundle exist.
**https://github.com/uvdesk/api-bundle**  so you can contribute and create issue here.

Check the instruction for for installing it once you finish with installation of this bundle You will see a api Icon in dashboard, and from here you can create a token and use for API request.

![postman](https://user-images.githubusercontent.com/42460055/72798732-affc4680-3c69-11ea-9cc6-dcf70f18a6a2.png)

If you still face any problem create a support ticket here.

https://support.uvdesk.com/en/customer/create-ticket/

**Comment by wkm97** [comment]
Okay, I will create an issue at the main repo.
